[profile.default]
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]
libs = ["lib"]
out = "out"
solc_version = "0.8.26"
src = "src"
optimizer = true
optimizer_steps = ""
optimizer_runs = 1000
dynamic_test_linking = true

[rpc_endpoints]
base = "${BASE_RPC_URL}"

[etherscan]
base = { key= "${ETHERSCAN_API_KEY}" }